package com.gvormbrock.test.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.*;

@Entity
@Table
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Country {

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @NotNull
    @Size(min = 3, max = 50, message = "Country Name must be minimum 3 characters and maximum 50 characters long")
    @Pattern(regexp = "^[A-Za-z]+$", message = "Must be only characters")
    String name;

    @NotNull
    @Size(min = 2, max = 3, message = "CountryCode must be minimum 2 characters and maximum 3 characters long")
    @Pattern(regexp = "^[A-Za-z]+$", message = "Must be only characters")
    private String countryCode;
}
