package com.gvormbrock.test.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.*;

@Entity
@Table
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Country {

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @NotNull
    @Size(min = 3, max = 100, message = "Country Name must be minimum 3 characters and maximum 100 characters long")
    String name;

    @NotNull
    @Size(min = 2, max = 2, message = "CountryCode must be exactly 2 characters long")
    private String countryCode;
}
