package com.gvormbrock.test.model;


import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.*;

import java.sql.Date;


@Entity
@Table(name = "USER_TABLE") // You must rename this class as user is a key word in sql
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class User {

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Size(min = 4, max = 6, message = "Gender must be minimum 4 characters and maximum 5 characters long")
    private String gender;

    @NotNull
    @Size(min = 3, max = 50, message = "Name must be minimum 3 characters and maximum 50 characters long")
    private String name;

    @NotNull
    Date birthday;

    @NotNull
    @ManyToOne(fetch = FetchType.EAGER)
    Country countryOfResidence;

    @Size(min = 2, max = 50, message = "Phone number must be minimum 2 characters and maximum 50 characters long")
    String phoneNumber;
}